# Generated by Django 4.2 on 2023-05-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrCode', models.ImageField(upload_to='img')),
                ('chave_pix', models.CharField(max_length=100)),
            ],
        ),
    ]
