# Generated by Django 4.2 on 2023-05-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=20)),
                ('imagens', models.ManyToManyField(to='plataforma.imagem')),
            ],
        ),
    ]
