# Generated by Django 4.2 on 2023-05-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='descricao_curta',
            field=models.CharField(default='Teste', max_length=50),
            preserve_default=False,
        ),
    ]
